//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void EMU_enter_DefaultMode_from_RESET(void);
extern void LFXO_enter_DefaultMode_from_RESET(void);
extern void CMU_enter_DefaultMode_from_RESET(void);
extern void ADC0_enter_DefaultMode_from_RESET(void);
extern void ACMP0_enter_DefaultMode_from_RESET(void);
extern void ACMP1_enter_DefaultMode_from_RESET(void);
extern void IDAC0_enter_DefaultMode_from_RESET(void);
extern void RTCC_enter_DefaultMode_from_RESET(void);
extern void USART0_enter_DefaultMode_from_RESET(void);
extern void USART1_enter_DefaultMode_from_RESET(void);
extern void LEUART0_enter_DefaultMode_from_RESET(void);
extern void WDOG0_enter_DefaultMode_from_RESET(void);
extern void I2C0_enter_DefaultMode_from_RESET(void);
extern void GPCRC_enter_DefaultMode_from_RESET(void);
extern void LDMA_enter_DefaultMode_from_RESET(void);
extern void TIMER0_enter_DefaultMode_from_RESET(void);
extern void TIMER1_enter_DefaultMode_from_RESET(void);
extern void LETIMER0_enter_DefaultMode_from_RESET(void);
extern void CRYOTIMER_enter_DefaultMode_from_RESET(void);
extern void PCNT0_enter_DefaultMode_from_RESET(void);
extern void PRS_enter_DefaultMode_from_RESET(void);
extern void PORTIO_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

// $[User-defined pin name abstraction]

#define BUZZER_PIN              (9)
#define BUZZER_PORT             (gpioPortC)

#define DS2482_CTRL_PIN         (12)
#define DS2482_CTRL_PORT        (gpioPortB)

#define LCD_DSP_PIN             (15)
#define LCD_DSP_PORT            (gpioPortD)

#define LCD_SCLK_PIN            (2)
#define LCD_SCLK_PORT           (gpioPortA)

#define LCD_SCS_PIN             (0)
#define LCD_SCS_PORT            (gpioPortA)

#define LCD_SI_PIN              (1)
#define LCD_SI_PORT             (gpioPortA)

#define LED_BLU_PIN             (13)
#define LED_BLU_PORT            (gpioPortD)

#define LED_GRN_PIN             (14)
#define LED_GRN_PORT            (gpioPortD)

#define LED_RED_PIN             (12)
#define LED_RED_PORT            (gpioPortD)

#define SCL_PIN                 (11)
#define SCL_PORT                (gpioPortC)

#define SDA_PIN                 (10)
#define SDA_PORT                (gpioPortC)

#define SW1_PIN                 (4)
#define SW1_PORT                (gpioPortA)

#define SW2_PIN                 (3)
#define SW2_PORT                (gpioPortA)

#define VBATT_CTRL_PIN          (11)
#define VBATT_CTRL_PORT         (gpioPortB)

#define VMEAS_CTRL_PIN          (8)
#define VMEAS_CTRL_PORT         (gpioPortC)

#define VREG27_CTRL_PIN         (5)
#define VREG27_CTRL_PORT        (gpioPortA)

// [User-defined pin name abstraction]$


#endif

