// Copyright 2025 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_appearance                       9
#define gattdb_firmware_revision_string         16
#define gattdb_hardware_revision_string         18
#define gattdb_serial_number_string            20
#define gattdb_ota_control                     23
#define gattdb_battery_level                   26
#define gattdb_characteristic_presentation_format         28
#define gattdb_temperature_reading_characteristic         31
#define gattdb_auto_sleep_interval_characteristic         35
#define gattdb_sleep_time_characteristic         37
#define gattdb_reset_sleep_timer_characteristic         39
#define gattdb_force_sleep_characteristic         41
#define gattdb_disconnect_characteristic         43
#define gattdb_display_scale_characteristic         45
#define gattdb_measurement_interval_characteristic         48
#define gattdb_thermometer_mode_characteristic         50
#define gattdb_emissivity_characteristic         53
#define gattdb_begin_calibration_characteristic         56
#define gattdb_laser_characteristic            58
#define gattdb_play_sound_characteristic         62
#define gattdb_legacy_temperature_as_ascii         65
#define gattdb_legacy_temperature_as_float         68
#define gattdb_legacy_measurement_scale         71
#define gattdb_legacy_measurement_timing         74
#define gattdb_legacy_auto_off_interval         76
#define gattdb_legacy_disconnect_peripheral         78
#define gattdb_legacy_reset_auto_off           80
#define gattdb_legacy_force_sleep              82
#define gattdb_legacy_sleep_time               84
#define gattdb_legacy_custom_probe_description         86
#define gattdb_rits_not_okay_to_record_characteristic         89
#define gattdb_rits_unlock_characteristic         92

typedef enum
{
    Default                        = 0x0001,
    Legacy_Blue2                   = 0x0002,
    Infrared                       = 0x0004,
    Sound                          = 0x0008,
    Rits                           = 0x0010,
    bg_gattdb_data_all_caps = 0x001f
} bg_gattdb_data_cap_t;

#endif
